---
compact: true
quiet: true # otherwise inline 'checkov:skip=' won't work
summary-position: top
download-external-modules: true # false
evaluate-variables: true
output: cli
skip-results-upload: true
framework:
  - all
# mask: []
# secrets-history-timeout: 12h
# secrets-scan-file-type: []
# block-list-secret-scan: []
# branch: master

dockerfile-path: Dockerfile

skip-path: # '/' is added to the path beginning
  - docs/.*.md
  - examples/.*.tf
  - indykite/resource_event_sink_test.go # CKV_SECRET_6

block-list-secret-scan:
  - docs/.*.md
  - examples/.*.tf
  - indykite/resource_event_sink_test.go # CKV_SECRET_6

skip-check:
  - CKV_SECRET_6 # FIXME: false positive on certain files as the above settings aren't honoured
