---
# https://terraform-docs.io/user-guide/configuration/

formatter: "markdown table"

# header-from: ".header.tf"
# footer-from: ".footer.tf"

recursive:
  enabled: false
  path: "modules"
  include-main: true

# sections:
#   hide: []
#   show: [providers, inputs, outputs]

# content: ""

# output:
#   file: ""
#   mode: inject
#   template: |-
#     <!-- BEGIN_TF_DOCS -->
#     {{ .Content }}
#     <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false # do NOT extract exact version of locally cached providers
  read-comments: true
  required: true
  sensitive: true
  type: true
