---
name: Image build for jarvis-proto
on:
    pull_request:
        branches:
            - master
        paths:
            - docker/**
permissions:
    contents: read
    id-token: write
jobs:
    build:
        name: Build and publish Test image
        env:
            ARTIFACT_REGISTRY_URL: europe-west1-docker.pkg.dev
            GCP_PROJECT_ID_MGMT: ${{ secrets.GCP_PROJECT_ID_MGMT }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            IMAGE_NAME: terraform-tests-for-local-jarvis
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v5
            - id: get_version
              run: |
                  version=`cat ./docker/local/ForJarvisProtoLocal.Dockerfile | sed -nr 's/.*version="(.+)"/\1/p'`
                  echo "version=$version" >> $GITHUB_OUTPUT
            - name: setup buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
            - name: Setup GCP Auth
              id: authentication
              uses: google-github-actions/auth@v3
              with:
                  workload_identity_provider: projects/581343830490/locations/global/workloadIdentityPools/github-mgmt/providers/github-mgmt-provider
                  service_account: github@${{ env.GCP_PROJECT_ID_MGMT }}.iam.gserviceaccount.com
            - name: login to artifact registry
              run: |
                  gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_URL }} -q
            - name: Build, Tag and Publish docker image
              run: |
                  cd docker/local
                  docker buildx build --push --squash --build-arg SSH_PRIVATE_KEY="${{ env.SSH_KEY }}" \
                  --tag ${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID_MGMT }}/indykite/${{ env.IMAGE_NAME }}:latest \
                  --tag ${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID_MGMT }}/indykite/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }} \
                  --platform linux/amd64,linux/arm64,linux/arm/v7 -f ForJarvisProtoLocal.Dockerfile .
