name: Image build for jarvis-proto
on:
  pull_request:
    branches:
        - master
    paths:
        - docker/**
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  build:
    name: Build and publish Test image
    env:
      GCR_URL: gcr.io
      GCP_PROJECT_ID: jarvis-dev-268314
      SSH_KEY: ${{ secrets.SSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - id: get_version
        run: |
          version=`cat ./docker/ForJarvisProtoLocal.Dockerfile | sed -nr 's/.*version="(.+)"/\1/p'`
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup GCP Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: 'projects/699926043561/locations/global/workloadIdentityPools/github-dev/providers/github-dev-provider'
            service_account: 'terraform-provider-indykite@jarvis-dev-268314.iam.gserviceaccount.com'
      - name: login to container registry
        run: |
            gcloud auth configure-docker -q
      - name: Build, Tag and Publish docker image
        run: |
            cd docker
            docker buildx build --push --squash --build-arg SSH_PRIVATE_KEY="${SSH_KEY}" --tag ${GCR_URL}/${GCP_PROJECT_ID}/test/terraform-tests-for-local-jarvis:latest --tag ${GCR_URL}/${GCP_PROJECT_ID}/test/terraform-tests-for-local-jarvis:${{ steps.get_version.outputs.version }} --platform linux/amd64,linux/arm64 -f ForJarvisProtoLocal.Dockerfile .
