---
name: Changelog
concurrency: jarvis-changelog
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        with:
          token: ${{ secrets.INDYKITEONE_PAT }}
