---
name: Docker Build
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - docker/**
  # to have an ability to run the workflow manually
  workflow_dispatch: {}
#
permissions:
  contents: read
  id-token: write # mint OIDC token for keyless GCP auth via Workload Identity Federation (setup-buildx step)
#
jobs:
  build:
    name: terraform-tests-for-local-jarvis
    env:
      IMAGE_NAME: terraform-tests-for-local-jarvis
      SSH_KEY: ${{ secrets.SSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: indykite/.github/.github/actions/git-checkout@master # actions/checkout with dynamic fetch-depth resolution

      - name: setup/env
        id: get_version
        run: |
          version=$(sed -nr 's/.*version="(.+)"/\1/p' ./docker/local/ForJarvisProtoLocal.Dockerfile)
          echo "version=${version}" >>"${GITHUB_OUTPUT}"

      - name: docker/build & push
        uses: indykite/.github/.github/actions/docker-build@master
        with:
          gcp-service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_MGMT }}
          docker-repository-uri: ${{ secrets.GCP_GAR_DOCKER }}
          docker-image-name: ${{ env.IMAGE_NAME }}
          docker-image-tag: ${{ steps.get_version.outputs.version }}
          docker-image-tag-latest: "1"
          docker-context: docker/local
          dockerfile: docker/local/ForJarvisProtoLocal.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: '{"SSH_PRIVATE_KEY":"${{ env.SSH_KEY }}"}'
          trivy-scan: "1"
          trivy-exit-code: "0"
