---
name: Lint
on:
    pull_request:
        types: [opened, synchronize, reopened]

    # Run on master too to save cache, which can be shared into PR too
    push:
        branches:
            - master

jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Run GolangCI-Lint Scanner
              uses: golangci/golangci-lint-action@v3
              with:
                  # Required: the version of golangci-lint is required and must be specified without patch version.
                  version: v1.55.2

                  # Optional: golangci-lint command line arguments.
                  args: --out-format=colored-line-number --timeout 2m00s

                  # https://github.com/golangci/golangci-lint-action/issues/135
                  skip-pkg-cache: true
