---
name: Lint
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened]

  # Run on master too to save cache, which can be shared into PR too
  push:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0 - https://github.com/actions/checkout/releases

      - name: setup/golang
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0 - https://github.com/actions/setup-go/releases
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0 - https://github.com/golangci/golangci-lint-action/releases
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version.
          version: v2.1

          # Optional: golangci-lint command line arguments.
          args: --config=.golangci.yml --timeout 3m00s
